### ISSUE TITLE
Hot reloading compability?

### ISSUE THREAD

**Issue by Misiur** [haxe-react/react-native#7]
Hello. [React-native hot reloading is a cool feature](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html). However, because we are working on a single haxe compiled js file it doesn't work. Any ideas how to make it work?

**Comment by kevinresol** [comment]
It does work. Check out the setting here: https://github.com/haxe-react/haxe-react-native-sample
Basically it works by having an extra js file to load the haxe generated js.

Though it could become very slow if your app is big due to the single js file. You can speed up by breaking up the generated js.
